name: hexfetch-windows

on:
  push:
    branches: [windows]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cargo test
        run: cargo test --verbose
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  build:
    name: Build (Windows)
    needs: test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Rename executable
        run: mv target/release/hexfetch-rs.exe hexfetch.exe
      - name: Generate Checksum
        if: github.event_name == 'release'
        shell: pwsh
        run: (Get-FileHash hexfetch.exe -Algorithm SHA256).Hash | Out-File -Encoding ASCII hexfetch.exe.sha256
      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hexfetch.exe
            hexfetch.exe.sha256
          draft: true
